version: '3'

services:
# Dependency Services
  db_marley: # MySQL Server
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - db_marley_data:/var/lib/mysql

  # Servers
  rest_service:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.rest
    volumes:
      - ../:/app
    ports:
      - 8000:8000

volumes:
  db_marley_data: