version: '3'

services:
# Dependency Services
  db_marley: # MySQL Server
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - db_marley_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis: # Redis Server used for Session Caching
    image: 'redis:alpine'
    command: redis-server --requirepass yourpasswordkkfkfa

# Application Servers
  backend: # REST Server for Posts
    build:
      context: ../backend
      dockerfile: ../infrastructure/Dockerfile.backend
    volumes:
      - ../backend:/app
    ports:
      - 8080:8080

  vision: # REST server for vision
    build:
      context: ../vision
      dockerfile: ../infrastructure/Dockerfile.vision
    ports:
      - 8003:8003

  frontend: # Server for fully client side ReactJS application
    build:
      context: ../frontend
      dockerfile: ../infrastructure/Dockerfile.frontend
    volumes:
      - ../frontend:/app
    ports:
      - 80:3000

volumes:
  db_marley_data: